Regression test
omicsNLP/Auto-CORPus pull request #48
Opened 2024-09-30 13:05 UTC by AdrianDAlessandro

This PR adds a regression test that can be run with `pytest`

The data used for this test is the Open Access publication describing this software: https://doi.org/10.3389/fdgth.2022.788124 - it is Creative Commons licensed and the html used for the test includes the Creative Commons license text inside it, which automatically makes it comply with the license, as far as I can tell.

2024-09-30 14:14 UTC, Thomas-Rowlands commented on tests/test_regression.py
> +    with open(Path(__file__).parent / "data" / "PMC8885717_abbreviations.json") as f:
encoding="utf-8" needed to resolve Windows 11 encoding error

2024-09-30 14:15 UTC, Thomas-Rowlands commented on tests/test_regression.py
> +    with open(Path(__file__).parent / "data" / "PMC8885717_tables.json") as f:
encoding="utf-8" needed to resolve Windows 11 encoding error

2024-09-30 14:16 UTC, Thomas-Rowlands requested changes
Added suggested changes to the test_regression.py file. Testing in Windows 11 throws an encoding error, which is resolved by specifying UTF-8. Looks good with this change however.

2024-10-02 12:40 UTC, AdrianDAlessandro commented
@Thomas-Rowlands I've updated it to specify utf-8 encoding. Can you approve this PR to run workflows so that we can see if the test is passing?

2024-10-02 14:48 UTC, Thomas-Rowlands approved these changes

2024-10-02 14:48 UTC, merged